name: Restart Hugging Face Space

on:
  workflow_dispatch:

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: Restart the Hugging Face Space
        run: |
          curl -X POST https://api.huggingface.co/spaces/YashGoyal06/backend/restart \
          -H "Authorization: Bearer ${{ secrets.HF_TOKEN }}"
